services:
    Symfony\Component\Security\Core\Authorization\AuthorizationChecker: '@security.authorization_checker'

    App\Service\Security\PasswordUpdaterInterface: '@App\Service\Security\PasswordUpdater'

    App\Service\Security\PasswordUpdater:
        class: App\Service\Security\PasswordUpdater

    App\Service\CanonicalizerInterface: '@App\Service\Canonicalizer'

    App\Service\Canonicalizer:
        class: App\Service\Canonicalizer

    App\Service\TokenGeneratorInterface: '@App\Service\TokenGenerator'

    App\Service\TokenGenerator:
        class: App\Service\TokenGenerator

    App\Event\Listener\TenantFilterConfiguratorListener:
        class: App\Event\Listener\TenantFilterConfiguratorListener
        tags:
            - { name: kernel.event_listener, event: kernel.request }
